# Generated by Django 5.2.1 on 2025-05-19 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Оценка",
                "verbose_name_plural": "Оценки",
            },
        ),
        migrations.RemoveConstraint(
            model_name="rating",
            name="unique_user_event_rating",
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["user", "event"], name="events_rati_user_id_01d9dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["created_at"], name="events_rati_created_76131c_idx"
            ),
        ),
    ]
