# Generated by Django 5.2.1 on 2025-05-19 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_events_even_created_52c227_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="seats",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Количество мест",
            ),
        ),
    ]
