# Generated by Django 5.2.1 on 2025-05-20 16:05

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_seats"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="event",
            name="ratings_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rating",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Оценка",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("user", "event")},
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["updated_at"], name="events_rati_updated_c9fcc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(fields=["score"], name="events_rati_score_75dcdd_idx"),
        ),
    ]
