# Generated by Django 5.2.1 on 2025-05-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_average_rating_event_ratings_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="average_rating",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=3
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="ratings_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
